Kurs/Areas/Admin/Models/MovieX.cs
using MovieDAL;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Kurs.Areas.Admin.Models
{

    public class MovieX
    {
        [CustomValidation (typeof(MovieValidatorClass), "NewMovie")]
        [Required]
        [MaxLength(30)]
        public string MovieId { get; set; }

        [MaxLength(100)]
        public string Title { get; set; }

        [MaxLength(100)]
        public string OriginalTitle { get; set; }

        public string Description { get; set; }

        [MaxLength(4)]
        public string ProductionYear { get; set; }

        public int RunningLengthHour { get; set; }

        public int RunningLengthMinute { get; set; }

        public int GenreId { get; set; }

    }


    public class MovieValidatorClass
    {
        public static ValidationResult NewMovie(string movieId)
        {
            ImdbContext db = new ImdbContext();
            if (db.Movies.Find(movieId) == null)
            {
                return ValidationResult.Success;
            }
            else
                return new ValidationResult("Filmen finnes fra før");
        }
    }
}

Kurs/Areas/Admin/Controllers/MovieController.cs
using Kurs.Areas.Admin.Models;
using MovieDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kurs.Areas.Admin.Controllers
{
    public class MovieController : Controller
    {
        ImdbContext db = new ImdbContext();

        // GET: Admin/Movie
        public ActionResult Index()
        {
            ViewData.Model = db.Movies;

            return View();
        }

        public ActionResult Create()
        {
            ViewBag.Genres = new SelectList(db.Genres, "GenreId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MovieX model)
        {
            ViewBag.Genres = new SelectList(db.Genres, "GenreId", "Name");

            if (ModelState.IsValid)
            {

                var movie = new Movie();
                movie.MovieId = model.MovieId;

                movie.OriginalTitle = model.OriginalTitle;
                movie.Title = model.Title;
                movie.Description = model.Description;
                movie.RunningLength = (model.RunningLengthHour * 60) + model.RunningLengthMinute;

                if (movie.RunningLength < 10)
                {
                    ModelState.AddModelError("RunningLengthHour", "Filmen er for kort");
                    ModelState.AddModelError("RunningLengthMinutes", "Filmen er for kort");
                    return View();
                }
                movie.ProductionYear = model.ProductionYear;
                movie.Genre = db.Genres.Find(model.GenreId);

                db.Movies.Add(movie);
                db.SaveChanges();

                return RedirectToAction("Index", "Movie");

            }

            return View();
        }

        public ActionResult Delete(string movieId)
        {
            var m = db.Movies.Find(movieId);
            if (m == null)
                return HttpNotFound();

            ViewData.Model = new MovieX
            return View("Index");
        }


    }
}

Kurs/Controllers/ImageController.cs
using MovieDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Kurs.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        [Route("Image/{format}/{id}.jpg")]
        public ActionResult CreateImage(string format, string id)
        {
            var pixel = 0;
            switch (format)
            {
                case "thumb":
                    pixel = 100;
                    break;
                case "medium":
                    pixel = 300;
                    break;
                default:
                    return HttpNotFound();
            }


            if (format.Equals("thumb")) pixel = 100;

            var db = new ImdbContext();

            var movie = db.Movies.Find(id);
            var filename = Server.MapPath("~/App_Data/covers/" + movie.MovieId + ".jpg");

            new WebImage(filename)
                .Resize(pixel, pixel)
                .Write();


            return new EmptyResult();

        }
    }
}

Kurs/Controllers/ImdbApiController.cs
using MovieDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Kurs.Controllers
{
    public class ImdbApiController : Controller
    {
        ImdbContext db = new ImdbContext();
        // GET: ImdbApi
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Movies()
        {
            //var db = new ImdbContext();
            //var movies = db.Movies;
            var doc = new XElement("movies", from movie in db.Movies.ToList()
                                             select new XElement("movie", 
                                                new XAttribute("id", movie.MovieId),
                                                movie.Title));
            return Content(doc.ToString(), "text/xml");
        }

        public ActionResult Details(string id)
        {

            var m = db.Movies.Find(id);
            var doc = new XElement("movie", new XElement("details",
                                                new XAttribute("id", m.MovieId), 
                                                new XAttribute("title", m.Title),
                                                new XAttribute("orgTitle", m.OriginalTitle),
                                                new XAttribute("prodar", m.ProductionYear),
                                                new XAttribute("lengde", m.RunningLength)
                                                     ));
            return Content(doc.ToString(), "text/xml");
        }


    }
}

Kurs/Controllers/MovieController.cs
using MovieDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kurs.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
    //    public ActionResult Index()
    //    {
    //        return View();
    //    }

            public ViewResult Index()
        {
            var db = new ImdbContext();
            var movies = db.Movies;
            ViewData.Model = movies;
            return View();
        }
        //public string Index()
        //{
        //    return "Hei";
        //}

        public ViewResult Details (string id)
        {
            var db = new ImdbContext();

            var movie = db.Movies.Find(id);
            ViewData.Model = movie;

            return View();
        }

        public string Genres()
        {
            return "Movie Genres()";
        }

        public string MoviesByGenre(string genrename)
        {
            return "Movie genre: " + genrename;
        }

    }
}

Kurs/Controllers/PersonController.cs
using MovieDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kurs.Controllers
{
    public class PersonController : Controller
    {
        // GET: Person
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public string Actors()
        {
            return "Din Actor ";
        }

        public ViewResult Details(int id)
        {
            var db = new ImdbContext();

            var person = db.Persons.Find(id);
            ViewData.Model = person;

            return View();
        }
    }
}

Kurs/Areas/Admin/Views/Movie/Create.cshtml
@model Kurs.Areas.Admin.Models.MovieX

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MovieId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OriginalTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OriginalTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OriginalTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductionYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductionYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunningLengthHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunningLengthHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RunningLengthHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunningLengthMinute, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunningLengthMinute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RunningLengthMinute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
                    model => model.GenreId,
                    (SelectList)ViewBag.Genres
                )
            </div>
        </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Kurs/Areas/Admin/Views/Movie/Index.cshtml
@model IEnumerable<MovieDAL.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductionYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RunningLength)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductionYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RunningLength)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MovieId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MovieId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MovieId })
        </td>
    </tr>
}

</table>

Kurs/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Kurs/Views/Movie/Details.cshtml
@model MovieDAL.Movie
@{
    ViewBag.Title = Model.Title;
}

<h2>@Model.Title (@Model.ProductionYear)</h2>
<p>@Model.Description</p>

<p>
    <img src="@Url.Action("CreateImage", "Image", new { format = "thumb", id = Model.MovieId}) "/>
</p>

<strong>Skuespillere</strong>
<ul>
    @foreach (var person in Model.Actors)
    {
        <li>
            @Html.ActionLink(@person.Name, "Details", "Person", new { id = @person.PersonId }, null)
        </li>
     
    }
</ul>

<strong>Produsenter</strong>
<ul>
    @foreach (var person in Model.Producers)
    {
        <li>@person.Name</li>
    }
</ul>

<strong>Regisør</strong>
<ul>
    @foreach (var person in Model.Directors)
    {
        <li>@person.Name</li>
    }
</ul>

Kurs/Views/Movie/Index.cshtml
@using MovieDAL
@model IEnumerable<Movie>
@{
    ViewBag.Title = "Index";
}

<h2>Liste over @Model.Count() filmer</h2>

<ul>
 @foreach (var movie in Model)
        {
            <li>
                @Html.ActionLink(movie.Title, "Details", "Movie", new { id = @movie.MovieId }, null)
            </li>
        }
</ul>

Kurs/Views/Person/Details.cshtml
@model MovieDAL.Person
@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>

<ul>
    @foreach (var movie in Model.ActedMovies)
    {
        <li>
            @Html.ActionLink(@movie.Title, "Details", "Movie", new { id = @movie.MovieId }, null)
        </li>
    }
</ul>

Kurs/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <img src="http://upload.wikimedia.org/wikipedia/en/4/48/Music_and_Video_club_%28MVC%29_logo.jpg" />
    <div>
        @RenderBody()
    </div>
    <p>
        Blah Blah Blah Blah Blah Blah Blah Blah
        <br />Copyright ....
    </p>
</body>
</html>